
import Navbar from './components/Navbar/Navbar'
import RegisterModel from './components/models/RegisterModel'
import './globals.css'
import { Nunito } from 'next/font/google'
import LoginModel from './components/models/LoginModel'
import getCurrentUser from './actions/getCurrentUsers'
import RentModel from './components/models/RentModel'
import ToasterProvider from './providers/ToasterProvider'
import ClientOnly from './components/ClientOnly'

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'AirBnb',
  description: 'Generated by Abdul Hadi',
}

export  default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
      <ClientOnly>
          <ToasterProvider />
          <LoginModel />
          <RegisterModel />
          <RentModel />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <div className='pb-20 pt-28'>
        {children}
        </div>
        </body>
    </html>
  )
}
